version: '3'
services:
  db:
    image: mysql:8.0
    container_name: "gomysql-db"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
#      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gomysql
      MYSQL_USER: gomysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    restart: always

  api:
    build: ./api
    container_name: "gomysql-api"
    volumes:
      - ./api:/app
    command: go run src/server.go
    ports:
    - "1323:1323"
    stdin_open: true
    tty: true
