on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get changed files
        run: |
          diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo ${diff}
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.40.1
      - name: Run golangci-lint
        run: |
          echo ${diff}
          golangci-lint run ${diff}
