name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: git config to get private repositories
        run: git config --global url.'https://${{ secrets.REVIEWDOG_TOKEN }}:x-oauth-basic@github.com/sambaiz'.insteadOf 'https://github.com/sambaiz'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true
  gocyclo:
    name: runner / gocyclo
    runs-on: ubuntu-latest
    steps:
      - name: git config to get private repositories
        run: git config --global url.'https://${{ secrets.REVIEWDOG_TOKEN }}:x-oauth-basic@github.com/sambaiz'.insteadOf 'https://github.com/sambaiz'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: gocyclo
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true
          tool_name: gocyclo
          golangci_lint_flags: "--config=.github/.golangci.yml --disable-all --tests=false -E gocyclo"
